### ISSUE TITLE
Fork blockchain project repos

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#10]
Create a new github org to host the core node repo, the miner repo, and their corresponding dependencies.

**Comment by macterra** [comment]
[Bounty-10](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-10) created.

**Comment by macterra** [comment]
Handoff to @Flaxscrip to create crowdfund

**Comment by Flaxscrip** [comment]
Address: https://btcpay552438.lndyn.com/apps/3kUMmjZNx1crPUDbFwZM7giL2noC/crowdfund
