### ISSUE TITLE
Develop project pitches

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#11]
Create a wiki describing an initial set of Cryptotechguru projects and how they relate.

**Comment by macterra** [comment]
[Bounty-11](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-11) created.

**Comment by macterra** [comment]
Handoff to @Flaxscrip to create crowdfund.

**Comment by Flaxscrip** [comment]
Bounty page: https://btcpay552438.lndyn.com/apps/3taMc9biFG3SzMoLhUCHycoeHyXJ/crowdfund
