### ISSUE TITLE
Launch Cryptonomicon game

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#12]
Develop the game to a point where we can bring in new players from outside Cryptotech.

**Comment by macterra** [comment]
[Bounty-12](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-12) created

**Comment by macterra** [comment]
Handoff to @Flaxscrip to create crowdfund

**Comment by Flaxscrip** [comment]
Address: https://btcpay552438.lndyn.com/apps/2HQyQww3K2b1jGjaEujMzDdin4dC/crowdfund
