### ISSUE TITLE
Select a multi-sig wallet for bounties

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/Cryptonomicon#13]
Select a multi-sig wallet to securely hold the private keys controlling funds allocated for bounties.

**Comment by Flaxscrip** [comment]
I want to formally document my current recommendation to use https://github.com/bitpay/copay as our initial software wallet to host the bounty donation keys.

**Comment by Flaxscrip** [comment]
Decision is based on the following criteria: 
1- recently maintained codebase
2- open source with verified compilable codebase
3- keys managed locally with simple recovery backup words
4- support for multi-sig
5- support for spending from selected UTXO

**Comment by Flaxscrip** [comment]
Recommendation of other wallets are welcome. I would ideally like to move the keys offline to a hardware wallet with the above capabilities if that exists.

**Comment by Flaxscrip** [comment]
After discussion with experienced community members in the Discord channel (they are welcome to chime in here), it became clear that additional requirements we needed:
6- Donor/Recipient privacy - Giving BTC transactions a modicum of privacy is difficult
7- Transaction management - Historical accounting of transactions
8- API integration for future automation

**Comment by Flaxscrip** [comment]
Based on these additional requirements, https://github.com/btcpayserver/ has been suggested as the superior technology.

**Comment by Flaxscrip** [comment]
Rapid setup of a BTC server will require a Bounty to pay for a hosting provider like https://dynamic.lunanode.com. I recommend a deposit of the equivalent of $300 to finance the bandwidth and processing time that will be require to synchronize a full BTC node.

**Comment by Flaxscrip** [comment]
I opened a bounty to cover for the cost of setting up a BTCPay server of Lunanode.

**Comment by Flaxscrip** [comment]
@macterra - Would you accept to be the [Keymaster](https://github.com/cryptotechguru/Cryptonomicon/tree/master/Roles/Keymaster) for this issue? 

I prepared a new WIP [Bounty 13](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-13) in the [Bounties Wiki page](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounties)

**Comment by macterra** [comment]
FTR I accept the role of Keymaster for #13

**Comment by macterra** [comment]
I created a new account on LunaNode and funded with USD300 (0.066241 BTC)

Launched [BTCPay Server](https://btcpay552438.lndyn.com/) with c-lightning and accelerated sync options

**Comment by macterra** [comment]
Created an [FAQ](https://github.com/macterra/Cryptonomicon/wiki/BTCPay-Server) for how to use the server to create and collect bounties.

**Comment by macterra** [comment]
Completed a trial run with a [test bounty](https://github.com/macterra/Cryptonomicon/wiki/Bounty-1)

**Comment by macterra** [comment]
[Bounty-13](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-13) created

**Comment by macterra** [comment]
Handoff to @Flaxscrip to create crowdfund

**Comment by Flaxscrip** [comment]
Bounty Address: https://btcpay552438.lndyn.com/apps/KX3myQ5v58jgLjk3x3zYrXUwSCC/crowdfund

**Comment by Kinetic-311** [comment]
I can take care of any Infrastructure and DevOps tasks and management/administration/systems. I have access to some services and hardware. Do we have a list of current infrastructure requirements? We can spin up some VM as needed on a visualization host. -- Also I'm guessing there will be Open source code but some tools and other things we'll want private, we can setup Git/Tortoise for example.

**Comment by Flaxscrip** [comment]
@Kinetic-311 - Thank you for the offer! Once we have enough bounties completed to run an MVP Testnet we will need not only miners but also full nodes, charting sites, analytics engines, etc. All these requirements will be planned out here. We already have a hosted server for BTCPay but other needs will certainly come up as the codebase and network mature.

**Comment by Flaxscrip** [comment]
I suggest we add a step under the "Complete" header in the [bounties process description](https://github.com/cryptotechguru/Cryptonomicon/tree/master/Projects/Bounties) to instruct the Treasurer to close the crowdfund address in BTCPay prior to releasing the bounty.
