### ISSUE TITLE
Rebrand blockchain

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#18]
Depends on #4 but it is possible to get started before the vote completes by developing a set a scripts that automate the renaming process to some extent.

**Comment by macterra** [comment]
Created [Bounty-18](https://github.com/cryptotechguru/Cryptonomicon/issues/18)

**Comment by macterra** [comment]
CoinGecko lists over 4300 tokens. I suggest we use that as the criterion for whether a name has been taken in the crypto space, e.g. https://www.coingecko.com/en/coins/ocean-protocol

**Comment by Flaxscrip** [comment]
Bounty address: https://bounty.cryptotech.guru/apps/4S4HYA3Cxamji8NKaaApdrS4fxfM/crowdfund

**Comment by Flaxscrip** [comment]
Moving back to "In Progress". We need our wiki to reflect the updated bech32 Tesseract-Core prefixes which changed recently. For reference, see Tesseract-Core issue discussion: https://github.com/cryptotechguru/tesseract-core/issues/1#issuecomment-489744215

**Comment by macterra** [comment]
OK I fixed the bech32 address example in the [miner wiki](https://github.com/cryptotechguru/bfgminer-sha3/wiki). Good catch!
