### ISSUE TITLE
Deploy block explorer

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#19]

**Comment by macterra** [comment]
Created [Bounty-19](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-19)

**Comment by macterra** [comment]
We are investigating how much effort would be necessary to adapt Blockstream's [esplora](https://blockstream.info/) block explorer for Tesseract. Esplora and two major components, the web front end and an indexer back end which connects to a full node (either Bitcoin or Blockstream's Liquid).

The front end [esplora](https://github.com/Blockstream/esplora) was very easy to get up and running in a development environment by connecting it to Blockstream's public back end REST API. The back end [electrs](https://github.com/Blockstream/electrs) (which is itself a Rust re-implementation of the Electrum wallet back end) is not easy to get running. 

First, the latest version did not build out of the box because it relies on a dependency in a developer branch that has since been merged upstream and removed. We were able to get a version electrs to run in a Docker container but it would not connect to Tesseract because it was checking for a minimal Bitcoin version. We created a new esplora branch of tesseract-core that fakes the version for electrs, but then discovered that electrs does sanity checks on the hashes assuming they are SHA256 so fail on Tesseract's SHA-3 hashes.

We were finally able to build electrs by reverting to an earlier version (before the now missing dependency) so we'll be able to see if we can disable the hash sanity checks. If we discover that the library dependencies also assume SHA256 we will likely have to abandon this investigation, at least until we have time to substitute the hash algorithm in Rust code.

**Comment by macterra** [comment]
After disabling all the sanity checks involving hashes there are still at least 5 places where the indexer computes the block hash from header data. In order to adapt the electrs indexer it would be necessary to refactor the code, substituting a SHA-3 hash. This is certainly possible, the electrs code already supports dependency injection of the relevant code using feature flags, for e.g. using the [Block class](https://github.com/ElementsProject/rust-elements/blob/master/src/block.rs) from Blockstream's [ElementsProject](https://github.com/ElementsProject) when electrs is configured for the Liquid blockchain, however it would probably take a few weeks of work including ramping up the Rust language. Maybe when time permits, but for now we will revert to adapting the half-finished Equibit block explorer.

**Comment by Flaxscrip** [comment]
Thank you for looking into esplora. Let's go with the old block explorer for now.

**Comment by macterra** [comment]
New block explorer up and running at http://explorer.tesseract-crypto.io/
![image](https://user-images.githubusercontent.com/434644/58209220-9c50a880-7cb4-11e9-91ef-d567555ce2c7.png)

**Comment by macterra** [comment]
I've opened [several issues](https://github.com/cryptotechguru/tesseract-explorer/issues) to triage (include in this bounty or defer?)

**Comment by Flaxscrip** [comment]
Bounty fully funded: https://bounty.cryptotech.guru/apps/3R74Af3q8ALdpkvKmiRBwwVGuBGT/crowdfund

**Comment by Flaxscrip** [comment]
Gatekeeper: Requirements Delivered. 
@macterra - please send a payment request.

**Comment by macterra** [comment]
[Payment request](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-19#payment-request) added @Flaxscrip
