### ISSUE TITLE
Deploy stats site

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#20]
Deploy a [statoshi](https://statoshi.info/) site for Tesseract testnet

**Comment by macterra** [comment]
Created [Bounty-20](https://github.com/cryptotechguru/Cryptonomicon/issues/20)

**Comment by macterra** [comment]
Progress report: we merged the statoshi changeset into a new branch [statoshi](https://github.com/cryptotechguru/tesseract-core/tree/statoshi) branched from tag v0.05.06. It builds and runs OK on Ubuntu but does not build on windows and the automated build fails because the tests take too long because of the additional instrumentation so there are currently no plans to merge to trunk.

**Comment by macterra** [comment]
Progress report: we investigated several ways to install the statsd/graphite/grafana stack: native installations and official and unofficial docker images. After a few false starts we landed on https://github.com/hazelcast/docker-grafana-graphite which combines all 3 layers into a single integrated container. This proved very easy to get up and running on a development laptop for testing.

We were able to display the current block height from the live testnet though it seems many metrics that should be available for display are missing from graphite so more debugging needed.
![image](https://user-images.githubusercontent.com/434644/57385747-ff085700-7180-11e9-8700-5a50b63ec664.png)

**Comment by macterra** [comment]
For future reference [Statoshi Developers Guide](https://medium.com/@lopp/statoshi-developer-s-guide-241ac9ab9993)

**Comment by macterra** [comment]
Progress report: the [stats site](http://stats.tesseract-crypto.io) is up and running.

![image](https://user-images.githubusercontent.com/434644/57551372-da55e000-7336-11e9-8530-f16f81d604da.png)

![image](https://user-images.githubusercontent.com/434644/57551440-125d2300-7337-11e9-9b88-3fe791228828.png)

![image](https://user-images.githubusercontent.com/434644/57551497-2b65d400-7337-11e9-83dc-14a29df83ef5.png)

TBD: incremental work to configure individual dashboards on an ongoing basis.

**Comment by Flaxscrip** [comment]
Beautiful!

**Comment by macterra** [comment]
Screencaps for the Deliverables section of the Bounty...

![image](https://user-images.githubusercontent.com/434644/58335102-de8dfd00-7e0e-11e9-89f4-642c49e53965.png)

![image](https://user-images.githubusercontent.com/434644/58335281-3e84a380-7e0f-11e9-97ce-d09e58f815a1.png)

![image](https://user-images.githubusercontent.com/434644/58335330-607e2600-7e0f-11e9-8ce4-2ef0b681a574.png)

**Comment by Flaxscrip** [comment]
Bounty fully funded: https://bounty.cryptotech.guru/apps/2iE5DK7PBz74qXJuuCa8i9EgGMqr/crowdfund

**Comment by Flaxscrip** [comment]
Gatekeeper: Requirements Delivered. 
@macterra - please send a payment request.

**Comment by macterra** [comment]
[Payment request](https://github.com/cryptotechguru/Cryptonomicon/wiki/Bounty-20#payment-request) added @Flaxscrip
