### ISSUE TITLE
Determine genesis block message

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#34]
Currently inherited from fork: `WSJ - 03/Jan/2018 - Billionaire Wagers Millions On Bitcoin`

We have an opportunity to choose a new message for posterity!

**Comment by macterra** [comment]
Only for completeness I'll propose that we keep the current message.

I will also propose; "Extropy: BEST DO IT SO" (from https://technolibertarian.fandom.com/wiki/Principles_of_Extropy)

**Comment by Flaxscrip** [comment]
This could be a good message, although still long: "Scientists create a neural decoder that translates brain activity into speech."

https://singularityhub.com/2019/05/01/scientists-created-a-neural-decoder-that-translates-brain-activity-into-speech/#sm.0001hira4o10yf5hxm81fqswgag8q

**Comment by Flaxscrip** [comment]
An opportunity for Tesseract in today's NYT? "Tesla Seeks to Raise $2 Billion in Sale of Stock and Debt"

https://www.nytimes.com/2019/05/02/business/tesla-stock-fundraising.html

**Comment by Flaxscrip** [comment]
"Stocks Fall as China’s Response to U.S. Tariffs Stokes Economic Anxiety" NYT Monday May 13th, 2019
