### ISSUE TITLE
Select new name for blockchain project

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#4]
The blockchain formerly known as Equibit needs a new name, ideally with all the qualities of a good brand: distinctive, memorable, easy to pronounce, easy to spell, emotionally appealing and positive connotations.

Let's collect options here (with attribution) and I'll add them to a [multi-vote on the wiki](https://github.com/cryptotechguru/Cryptonomicon/wiki/Vote-4).

**Comment by macterra** [comment]
First option (and current name) is OCEAN suggested by @Flaxscrip which stands for "Open Crypto Equity and Assets Network".

One of the main reasons for revisiting the name is that it was noted in Discord that there would be significant brand confusion potential with https://oceanprotocol.com/

**Comment by macterra** [comment]
I suggested 3 options:
* Aquabit (a punny combination of Equibit and OCEAN)
* Muskox (just a whimsical name to get the brainstorming going)
* Meridion (a serious suggestion, based on the Greek word μερίδιο meaning "shares")

**Comment by macterra** [comment]
Sanchicharro suggested:
* OEN (Open Equity Network)
* ODEN (Open Decentralized Equity Network)
* DEN (Decentralized Equity Network)
* Opquity
* Nequity

**Comment by macterra** [comment]
Sigma suggested:
* Pepe (Potential Exponential Protocol Exchange)

**Comment by macterra** [comment]
CoinGecko lists over 4300 tokens. I suggest we use that as the criterion for whether a name has been taken in the crypto space, e.g. https://www.coingecko.com/en/coins/ocean-protocol

**Comment by macterra** [comment]
I propose: Securibit

Kind of a play on Equibit/equibity, Securibit/security

Also one of the main features is SHA-3 for enhanced security

**Comment by Kinetic-311** [comment]
Proposing "EquiByte" - Springboard on any success and contacts (IE Russia Today) Equibit might have had and use the story of keeping the project going. People like overcomer's.

**Comment by Flaxscrip** [comment]
Proposing "Tesseract" - 4-dimentional safety cube for all your securities needs! https://en.wikipedia.org/wiki/Tesseract

**Comment by Kinetic-311** [comment]
Good point there. Extra value added services like data modeling and warehousing could be a real need.

**Comment by macterra** [comment]
I designed a tesseract logo back in 2010 that could be repurposed for our blockchain...
![image](https://user-images.githubusercontent.com/434644/56229069-12734700-6047-11e9-9e57-619508f8e175.png)

**Comment by Flaxscrip** [comment]
Now that the votes are in (https://github.com/cryptotechguru/Cryptonomicon/wiki/Vote-4) I'd like to submit a pull request to change the following: 

README.md and OCEAN.md in https://github.com/cryptotechguru/Cryptonomicon/tree/master/Projects

With regards to OCEAN.md, should we rename the file to Tesseract.md OR add a "deprecated" comment at the top of OCEAN.md and create a new Tesseract.md?

Thoughts?

**Comment by macterra** [comment]
OCEAN.md should be renamed in one commit and modified in a separate so that git can track its provenance. (If you rename and modify in a single commit git will just see it as a file deletion and a separate file addition.)

**Comment by macterra** [comment]
FTR final result: Tesseract
