### ISSUE TITLE
Bounty Released stage

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#42]
A "Bounty Released" stage has been added to the Bounty projects board. This stage is missing from the ones specified in the [Bounties](https://cryptotechguru.github.io/Cryptonomicon/Projects/Bounties/) rules. Should we change the rules or remove the kanban column?

![image](https://user-images.githubusercontent.com/434644/57797441-75c0c980-7718-11e9-8086-017b7eb16414.png)

**Comment by Flaxscrip** [comment]
I don't think we need that stage. I created it as a Stage when I wanted to notify what payment had been made. We can achieve the same goal on the Bounty page by linking the payment transaction id.

**Comment by Flaxscrip** [comment]
Do you agree to remove the Kanban column?

**Comment by macterra** [comment]
Agreed. I will take care of it and close this issue.
