### ISSUE TITLE
Launch Tesseract mainnet

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#47]

**Comment by macterra** [comment]
Parameters we should consider changing for mainnet:

- remove premine
- update genesis block message
- update genesis block timestamp
- bech32 prefix 
- default ports
- max supply

**Comment by macterra** [comment]
Should probably also merge in the `statoshi2` branch so we don't need to maintain separate versions to support the grafana dashboards.

**Comment by macterra** [comment]
Removing the premine is pretty straightforward, mostly just deciding whether to comment it out or remove the code altogether. I'm leaning toward the latter so there is no confusion. Also need to remember to update any automated tests broken by the change.

**Comment by macterra** [comment]
Current genesis block message is `WSJ - 03/Jan/2018 - Billionaire Wagers Millions On Bitcoin`

Proposed new message: `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence/pub/` which is A _Declaration of the Independence of Cyberspace_ published as a [metatron asset](https://ipfs.io/ipfs/QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence/pub/)

The proposed message likely has too many characters to fit in the genesis block so maybe just `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence` or minimally `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5`

Or I could republish as `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyber-ind/pub/` or something that will fit.

**Comment by macterra** [comment]
> Should probably also merge in the `statoshi2` branch so we don't need to maintain separate versions to support the grafana dashboards.

Update: easy to merge but it caused the unit tests to fail for unrelated reasons (running out of file handles). In short term probably easier to maintain the statoshi branch separately.

**Comment by macterra** [comment]
> Proposed new message: `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence/pub/` which is A _Declaration of the Independence of Cyberspace_ published as a [metatron asset](https://ipfs.io/ipfs/QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence/pub/)
> 
> The proposed message likely has too many characters to fit in the genesis block so maybe just `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5/cyberspace-independence` or minimally `QmcSzKcziTP3kf8gM5bekMkqD7SVZf1Ve5eVEV7RZE14C5`

Update: turns out the character limit was my misunderstanding. I took the liberty of adding the protocol to the start: `ipfs://QmaVyAGXU4J5DjMZDK88F9S24rCVtS6dXfu8Xfvt35vL2W/cyberspace-independence/pub/`

**Comment by Flaxscrip** [comment]
Fantastic work David. I'm installing a new production node at home. 

@macterra Question: Should I just continue to CPU mine or should I try mine with a GPU for Mainnet?

**Comment by macterra** [comment]
For the record, I recommend just CPU mining until we can both start GPU mining consistently.

Main net currently has a block height of 689. I'll close this issue when we get to 1000.

**Comment by macterra** [comment]
To elaborate on the last point, if one of us starts GPU mining and drives up the difficulty then goes offline, then the remaining CPU miner could take more than a week to mine the next block.

**Comment by Flaxscrip** [comment]
My goal was to increase a little bit the security of the network, but a few GPUs don't even achieve that goal. I'll launch a CPU miner too.

**Comment by macterra** [comment]
Block height is 1045
