### ISSUE TITLE
Launch grafana dashboard for mainnet

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#49]
Reuse the one for [testnet](http://stats.tesseract-crypto.io/dashboard/db/transactions?refresh=10s&orgId=1&from=now-6h&to=now) or run both in parallel?

**Comment by Flaxscrip** [comment]
I believe we should keep the testnet alive (need a name). Just for continuity and historical purposes. That doesn't mean we need to keep all the tools online. Is the grafana dashboard costing you?

**Comment by macterra** [comment]
The dashboard is [up and running](http://stats.tesseract-crypto.io/dashboard/db/transactions?refresh=10s&orgId=1) on my google cloud instance alongside the TESS seed nodes and spam nodes. It may be possible to run the testnet dashboard side by side with more work, I would have to resolve port collisions and docker container name collisions.
