### ISSUE TITLE
Add rules for bounties

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/Cryptonomicon#6]
Bounties will provide a mechanism for funding tasks in projects. We will need to introduce new support roles: Gatekeeper (manager requirements and testing), KeyMaster (developer), and Treasurer (bounty escrow).

**Comment by Flaxscrip** [comment]
I'll add a responsibility for the Treasurer and GateKeeper to evaluate the Bounty's estimate (S, M, L, XL) valuation in terms of market prices in the payment currency. In other words, the Treasurer SHOULD (or MUST?) confirm the fair market value of the bounty payment.
